pool:
  name: default

trigger: none
jobs:
  - job: BuildAndTests
    displayName: "Build docker image and run tests"
    steps:
      - task: VSBuild@1
        inputs:
          solution: '**\*.sln'
          configuration: 'Release'
          clean: true