pool:
  name: default

trigger: none
jobs:
  - job: Build
    steps:
      - task: VSBuild@1
        inputs:
          solution: '**\*.sln'
          configuration: 'Release'
          clean: true
      - task: CopyFiles@2    
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'    
        inputs:    
          SourceFolder: '$(system.defaultworkingdirectory)'    
          Contents: '**/bin/Release/Database.dacpac'    
          TargetFolder: '$(build.artifactstagingdirectory)'    
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactstagingdirectory)'
          artifact: 'Database'
          publishLocation: 'pipeline'