pool:
  name: default

trigger: none
jobs:
  - job: Build
    steps:
      - task: VSBuild@1
        inputs:
          solution: '**\*.sln'
          configuration: 'Release'
          clean: true
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'bin/Release/Public.Database.dacpac'
          artifact: 'Public.Database'
          publishLocation: 'pipeline'