pool:
  name: default

trigger: none
jobs:
  - job: Build
    steps:
      - task: VSBuild@1
        inputs:
          solution: '**\*.sln'
          configuration: 'Release'
          clean: true
      - task: CopyFiles@2    
        inputs:
          SourceFolder: '$(system.defaultworkingdirectory)'
          Contents: '**/bin/Release/Public.Database.dacpac'
          TargetFolder: '$(build.artifactstagingdirectory)'
          flattenFolders: true
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactstagingdirectory)'
          artifact: 'Public.Database'
          publishLocation: 'pipeline'