CREATE TABLE ImageGroups
(
	Id BIGINT IDENTITY(1,1) NOT NULL,
	[Guid] UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
	[Name] NVARCHAR(50) NOT NULL,
	[Type] BIGINT NOT NULL, 

	CreatedBy BIGINT NOT NULL,
	CreatedOn DATETIME2(0) NOT NULL,
	ModifiedBy BIGINT NULL,
	ModifiedOn DATETIME2(0) NULL,

	IsTest BIT NOT NULL DEFAULT(0),

	CONSTRAINT PK_ImageGroups PRIMARY KEY CLUSTERED (Id ASC),
	CONSTRAINT UQ_ImageGroups_Guid UNIQUE ([Guid] ASC),
	CONSTRAINT FK_ImageGroups_Type FOREIGN KEY(Type) REFERENCES ImageTypes (Id),
	CONSTRAINT FK_ImageGroups_CreatedBy FOREIGN KEY(CreatedBy) REFERENCES Users (Id),
	CONSTRAINT FK_ImageGroups_ModifiedBy FOREIGN KEY(ModifiedBy) REFERENCES Users (Id)
)