CREATE TABLE ImageTypes
(
	Id BIGINT IDENTITY(1,1) NOT NULL,
	[Guid] UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
	Abbreviation NVARCHAR(4) NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,

	CreatedBy BIGINT NOT NULL,
	CreatedOn DATETIME2(0) NOT NULL,
	ModifiedBy BIGINT NULL,
	ModifiedOn DATETIME2(0) NULL,

	IsTest BIT NOT NULL DEFAULT(0),

	CONSTRAINT PK_ImageTypes PRIMARY KEY CLUSTERED (Id ASC),
	CONSTRAINT UQ_ImageTypes_Guid UNIQUE ([Guid] ASC),
	CONSTRAINT FK_ImageTypes_CreatedBy FOREIGN KEY(CreatedBy) REFERENCES Users (Id),
	CONSTRAINT FK_ImageTypes_ModifiedBy FOREIGN KEY(ModifiedBy) REFERENCES Users (Id)
)