CREATE TABLE Users
(
	Id BIGINT IDENTITY(1,1) NOT NULL,
	[Guid] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50) NOT NULL,

	CreatedBy NVARCHAR(50) NOT NULL,
	CreatedOn DATETIME2(0) NOT NULL,
	ModifiedBy NVARCHAR(50) NULL,
	ModifiedOn DATETIME2(0) NULL,
	
	CONSTRAINT PK_Users PRIMARY KEY CLUSTERED (Id ASC),
)