CREATE TABLE Users
(
	Id BIGINT IDENTITY(1,1) NOT NULL,
	[Guid] UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
	[Name] NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50) NOT NULL,

	CreatedBy BIGINT NOT NULL,
	CreatedOn DATETIME2(0) NOT NULL,
	ModifiedBy BIGINT NULL,
	ModifiedOn DATETIME2(0) NULL,
	
	CONSTRAINT PK_Users PRIMARY KEY CLUSTERED (Id ASC),
	CONSTRAINT UQ_Users_Guid UNIQUE ([Guid] ASC),
	CONSTRAINT FK_Users_Users FOREIGN KEY(CreatedBy) REFERENCES Users (Id),
	CONSTRAINT FK_Users_CreatedBy FOREIGN KEY(CreatedBy) REFERENCES Users (Id),
	CONSTRAINT FK_Users_ModifiedBy FOREIGN KEY(ModifiedBy) REFERENCES Users (Id)
)